src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone_number;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }
}

src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('last_name')
            ->add('phone_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ContactRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/contact")
 */
class ContactController extends AbstractController
{
    /**
     * @Route("/", name="app_contact_index", methods={"GET"})
     */
    public function index(ContactRepository $contactRepository): Response
    {
        return $this->render('contact/index.html.twig', [
            'contacts' => $contactRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_contact_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ContactRepository $contactRepository): Response
    {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactRepository->add($contact);
            return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contact/new.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_contact_show", methods={"GET"})
     */
    public function show(Contact $contact): Response
    {
        return $this->render('contact/show.html.twig', [
            'contact' => $contact,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_contact_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Contact $contact, ContactRepository $contactRepository): Response
    {
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactRepository->add($contact);
            return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contact/edit.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_contact_delete", methods={"POST"})
     */
    public function delete(Request $request, Contact $contact, ContactRepository $contactRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contact->getId(), $request->request->get('_token'))) {
            $contactRepository->remove($contact);
        }

        return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contact/_delete_form.html.twig
<form method="post" action="{{ path('app_contact_delete', {'id': contact.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
    <button class="btn btn-danger my-3">Delete</button>
</form>

templates/contact/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-lg my-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contact/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Contact{% endblock %}

{% block body %}
<div class="container">
    <h1>Edit Contact</h1>

    {{ include('contact/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contact_index') }}"  class="btn btn-info" role="button">back to list</a>

    {{ include('contact/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact index{% endblock %}

{% block body %}
<div class="container">
    <h1>Contact index</h1>

    <table class="table">
        <thead>
            <tr>

                <th>Name</th>
                <th>Last_name</th>
                <th>Phone_number</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contact in contacts %}
            <tr>

                <td>{{ contact.name }}</td>
                <td>{{ contact.lastName }}</td>
                <td>{{ contact.phoneNumber }}</td>
                <td>
                    <a href="{{ path('app_contact_show', {'id': contact.id}) }}">show</a>
                    <a href="{{ path('app_contact_edit', {'id': contact.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_contact_new') }}"  class="btn btn-info" role="button">Create new</a>
</div>
{% endblock %}

templates/contact/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Contact{% endblock %}

{% block body %}
<div class="container">
    <h1>Create new Contact</h1>

    {{ include('contact/_form.html.twig') }}

    <a href="{{ path('app_contact_index') }}"  class="btn btn-info" role="button">back to list</a>
</div>
{% endblock %}

templates/contact/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}
<div class="container">
    <h1>Contact</h1>

    <table class="table" >
        <tbody>

            <tr>
                <th>Name</th>
                <td>{{ contact.name }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ contact.lastName }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ contact.phoneNumber }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contact_index') }}" class="btn btn-info" role="button">back to list</a>

    <a href="{{ path('app_contact_edit', {'id': contact.id}) }}"  class="btn btn-info" role="button">edit</a>

    {{ include('contact/_delete_form.html.twig') }}
</div>
{% endblock %}